version: 2

models:
  - name: stg_orders
    description: Cleaned and standardized orders data
    columns:
      - name: order_id
        description: Primary key of the orders table
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers table
        tests:
          - not_null
      - name: amount
        description: Order amount in USD
        tests:
          - not_null
          - positive_values:
              zero_allowed: true

sources:
  - name: raw
    description: Raw data from our operational systems
    tables:
      - name: orders
        description: Raw orders data
        columns:
          - name: order_id
          - name: customer_id
          - name: order_date
          - name: status
          - name: amount 