version: 2

models:
  - name: dim_users
    description: "User dimension table with enriched data"
    columns:
      - name: user_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: full_name
        description: "User's full name"
        tests:
          - not_null
      - name: country_code
        description: "User's country code"
        tests:
          - not_null
      - name: region
        description: "Derived region based on country"
        tests:
          - not_null
          - accepted_values:
              values: ['North America', 'Europe', 'Other'] 